import type { Dialect } from "./dialect";

const ID_COLUMNS = new Set([
	"uuid",
	"project",
	"project_id",
	"customer",
	"invoice",
	"item",
	"credit_note",
	"invoice_item",
	"transaction_id",
	"parent_transaction",
	"recurring",
	"redeemed_project",
	"member",
	"signature_version",
	"claim_token",
	"expense",
	"source_id",
	"store_category",
	"parent_category",
	"ticket",
	"record",
	"run",
	"proforma",
	"entry",
	"reverses",
	"ledger_account",
	"recorded_invoice",
	"statement",
	"match_id",
	"payment_transaction",
]);

const TEXT_LENGTHS: Record<string, number> = {
	username: 30,
	account_username: 30,
	account: 30,
	created_by: 30,
	published_by: 30,
	invited_by: 30,
	redeemed_by: 30,
	locked_by: 30,
	unlocked_by: 30,
	sent_by: 30,
	email: 254,
	buyer_email: 254,
	token_hash: 64,
	credential_hash: 64,
	server_id: 32,
	signature_hash: 64,
	sha256: 64,
	invitation_email: 254,
	apikey: 128,
	apikey2: 128,
	invitation_token: 128,
	full_name: 150,
	issuer_name: 150,
	storage_key: 255,
	archive_key: 255,
	archive_sha256: 64,
	attachment_storage_key: 255,
	file_name: 250,
	content_type: 100,
	status: 32,
	period: 7,
	day: 64,
	reference: 64,
	number: 64,
	wallet_key: 64,
	processor: 32,
	code: 255,
	secret: 500,
	currency: 16,
	source: 32,
	kind: 64,
	address: 255,
	key: 128,
	date_format: 32,
	time_format: 32,
	timezone: 100,
	language: 32,
	accent_color: 32,
	invoice_format: 30,
	store_name: 200,
	order_format: 30,
	proforma_format: 30,
	proforma_settlement: 16,
	settlement: 16,
	document_type: 16,
	role: 32,
	interval_unit: 16,
	supply_type: 32,
	tax_category: 32,
	environment: 16,
	premise_id: 20,
	device_id: 20,
	invoice_number: 20,
	eor: 36,
	zoi: 32,
	slug: 100,
	domain: 253,
	attribute: 100,
	attribute_value: 200,
	fulfillment: 32,
	unit: 8,
	work_date: 10,
	starts_on: 10,
	ends_on: 10,
	started_on: 10,
	ended_on: 10,
	holiday_date: 10,
	due_on: 10,
	operation: 32,
	priority: 16,
	employment_type: 32,
	pay_type: 16,
	record_type: 32,
	changed_by: 30,
	decided_by: 30,
	updated_by: 30,
	author: 30,
	author_email: 254,
	reported_by: 254,
	person: 150,
	employee_number: 64,
	rates_period: 7,
	pay_date: 10,
	finalized_by: 30,
	verified_by: 30,
	source_type: 32,
	system_key: 64,
	account_kind: 16,
	expense_category: 80,
	posted_by: 30,
	payment_account: 16,
	asset_category: 32,
	bookkeeping: 32,
	closed_by: 30,
	reopened_by: 30,
	iban: 34,
	statement_id: 140,
	match_type: 32,
	matched_by: 30,
};

export function schemaTypes(dialect: Dialect) {
	return {
		int64: dialect === "sqlite" ? "INTEGER" : "BIGINT",
		flag: dialect === "sqlite" ? "INTEGER" : "SMALLINT",
		float: dialect === "sqlite" ? "REAL" : dialect === "mysql" ? "DOUBLE" : "DOUBLE PRECISION",
		text(name: string): string {
			if (dialect === "sqlite") return "TEXT";
			if (ID_COLUMNS.has(name)) return "VARCHAR(36)";
			const length = TEXT_LENGTHS[name];
			return length ? `VARCHAR(${length})` : dialect === "mysql" ? "LONGTEXT" : "TEXT";
		},
	};
}
