import type { SQL } from "bun";

import type { Dialect } from "./dialect";
import { schemaTypes } from "./schema-types";

export type { Dialect } from "./dialect";

export async function run(sql: SQL, dialect: Dialect, statements: string[]) {
	for (let statement of statements) {
		const index = statement.match(/^CREATE (?:UNIQUE )?INDEX (?:IF NOT EXISTS )?(\w+) ON (\w+)/);
		if (dialect === "mysql" && index) {
			const rows =
				await sql`SELECT INDEX_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ${index[2]} AND INDEX_NAME = ${index[1]}`;
			if (rows.length) continue;
			statement = statement.replace("INDEX IF NOT EXISTS", "INDEX");
		}
		if (dialect === "mysql" && statement.startsWith("CREATE TABLE")) {
			statement += " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin";
		}
		await sql.unsafe(statement);
	}
}

export async function createSchema(sql: SQL, dialect: Dialect) {
	const types = schemaTypes(dialect);
	return run(sql, dialect, [
		`CREATE TABLE IF NOT EXISTS accounts(
					username ${types.text("username")} PRIMARY KEY,
					email ${types.text("email")} NOT NULL UNIQUE,
					password ${types.text("password")} NOT NULL,
					two_factor_secret ${types.text("two_factor_secret")},
					status ${types.text("status")} DEFAULT 'active',
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					accessed ${types.int64} NOT NULL,
					admin ${types.flag} NOT NULL DEFAULT 0 CHECK (admin IN (0, 1))
				)`,
		`CREATE TABLE IF NOT EXISTS projects(
					uuid ${types.text("uuid")} PRIMARY KEY,
					name ${types.text("name")} NOT NULL,
					apikey ${types.text("apikey")} NOT NULL UNIQUE,
					apikey2 ${types.text("apikey2")} NOT NULL UNIQUE,
					webhook_url ${types.text("webhook_url")},
					webhook_secret ${types.text("webhook_secret")},
					status ${types.text("status")} DEFAULT 'active',
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					created_by ${types.text("created_by")} NOT NULL,
					currency ${types.text("currency")} NOT NULL DEFAULT 'EUR',
					display_name ${types.text("display_name")},
					date_format ${types.text("date_format")} NOT NULL DEFAULT 'auto',
					time_format ${types.text("time_format")} NOT NULL DEFAULT '24',
					timezone ${types.text("timezone")} NOT NULL DEFAULT 'Europe/Ljubljana',
					language ${types.text("language")} NOT NULL DEFAULT 'en',
					accent_color ${types.text("accent_color")},
					tax_country ${types.text("tax_country")},
					vat_status ${types.text("vat_status")},
					oss_registered ${types.flag} NOT NULL DEFAULT 0 CHECK (oss_registered IN (0, 1)),
					tax_currency ${types.text("tax_currency")},
					vat_exemption_note ${types.text("vat_exemption_note")},
					pos_custom_amounts ${types.flag} NOT NULL DEFAULT 1 CHECK (pos_custom_amounts IN (0, 1)),
					email_reminders ${types.flag} NOT NULL DEFAULT 0 CHECK (email_reminders IN (0, 1)),
					reminder_days_before INTEGER NOT NULL DEFAULT 3,
					reminder_days_after INTEGER NOT NULL DEFAULT 3,
					free_transactions ${types.int64},
					paid_transactions ${types.int64} NOT NULL DEFAULT 0,
					paid_storage_bytes ${types.int64} NOT NULL DEFAULT 0,
					white_label_until ${types.int64},
					logo_updated ${types.int64},
					email_server ${types.text("email_server")},
					invoice_format ${types.text("invoice_format")} NOT NULL DEFAULT 'YYMMDDXXXXXX',
					email_attach_invoice ${types.flag} NOT NULL DEFAULT 0 CHECK (email_attach_invoice IN (0, 1)),
					email_pay_link ${types.flag} NOT NULL DEFAULT 1 CHECK (email_pay_link IN (0, 1)),
					email_portal_link ${types.flag} NOT NULL DEFAULT 1 CHECK (email_portal_link IN (0, 1)),
					invoice_issuer_details ${types.flag} NOT NULL DEFAULT 1 CHECK (invoice_issuer_details IN (0, 1))
				)`,
		`CREATE TABLE IF NOT EXISTS project_members(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project_id ${types.text("project_id")} NOT NULL,
					account_username ${types.text("account_username")},
					role ${types.text("role")} NOT NULL,
					invited_by ${types.text("invited_by")},
					invitation_token ${types.text("invitation_token")},
					invitation_email ${types.text("invitation_email")},
					status ${types.text("status")} DEFAULT 'active',
					additional_permissions ${types.text("additional_permissions")},
					restricted_permissions ${types.text("restricted_permissions")},
					notes ${types.text("notes")},
					full_name ${types.text("full_name")},
					accepted_at ${types.int64},
					expires_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project_id) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (account_username) REFERENCES accounts(username) ON DELETE CASCADE,
					FOREIGN KEY (invited_by) REFERENCES accounts(username) ON DELETE SET NULL,
					UNIQUE(project_id, account_username),
					CHECK (role IN ('owner', 'admin', 'manager', 'accountant', 'developer', 'viewer', 'cashier'))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_project_members_project ON project_members(project_id)`,
		`CREATE INDEX IF NOT EXISTS idx_project_members_account ON project_members(account_username)`,
		`CREATE INDEX IF NOT EXISTS idx_project_members_status ON project_members(status)`,
		`CREATE INDEX IF NOT EXISTS idx_project_members_token ON project_members(invitation_token)`,
		`CREATE TABLE IF NOT EXISTS signature_assets(
					signature_hash ${types.text("signature_hash")} PRIMARY KEY,
					data ${types.text("data")} NOT NULL,
					created ${types.int64} NOT NULL
				)`,
		`CREATE TABLE IF NOT EXISTS project_member_signature_versions(
					uuid ${types.text("uuid")} PRIMARY KEY,
					member ${types.text("member")},
					signature_hash ${types.text("signature_hash")} NOT NULL,
					valid_from ${types.int64} NOT NULL,
					valid_until ${types.int64},
					FOREIGN KEY (member) REFERENCES project_members(uuid) ON DELETE SET NULL,
					FOREIGN KEY (signature_hash) REFERENCES signature_assets(signature_hash)
				)`,
		`CREATE INDEX IF NOT EXISTS idx_member_signature_versions_active
					ON project_member_signature_versions(member, valid_until, valid_from)`,
		`CREATE TABLE IF NOT EXISTS project_company(
					project ${types.text("project")} PRIMARY KEY,
					legal_name ${types.text("legal_name")},
					address_line1 ${types.text("address_line1")},
					address_line2 ${types.text("address_line2")},
					postal_code ${types.text("postal_code")},
					city ${types.text("city")},
					state ${types.text("state")},
					country ${types.text("country")},
					vat_number ${types.text("vat_number")},
					tax_number ${types.text("tax_number")},
					registration_number ${types.text("registration_number")},
					email ${types.text("email")},
					phone ${types.text("phone")},
					website ${types.text("website")},
					footer_note ${types.text("footer_note")},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS project_logos(
					project ${types.text("project")} PRIMARY KEY,
					content_type ${types.text("content_type")} NOT NULL,
					data ${types.text("data")} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS project_usage(
					project ${types.text("project")} NOT NULL,
					period ${types.text("period")} NOT NULL,
					free_used ${types.int64} NOT NULL DEFAULT 0,
					paid_used ${types.int64} NOT NULL DEFAULT 0,
					PRIMARY KEY (project, period),
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS access_logs(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project_id ${types.text("project_id")},
					account_username ${types.text("account_username")} NOT NULL,
					action ${types.text("action")} NOT NULL,
					resource_type ${types.text("resource_type")},
					resource_id ${types.text("resource_id")},
					permission_checked ${types.text("permission_checked")},
					granted ${types.flag} CHECK (granted IN (0, 1)),
					ip_address ${types.text("ip_address")},
					user_agent ${types.text("user_agent")},
					metadata ${types.text("metadata")},
					created ${types.int64} NOT NULL,
					FOREIGN KEY (project_id) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (account_username) REFERENCES accounts(username) ON DELETE CASCADE
				)`,
		`CREATE INDEX IF NOT EXISTS idx_access_logs_project ON access_logs(project_id)`,
		`CREATE INDEX IF NOT EXISTS idx_access_logs_account ON access_logs(account_username)`,
		`CREATE INDEX IF NOT EXISTS idx_access_logs_created ON access_logs(created)`,
		`CREATE TABLE IF NOT EXISTS audit_log(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")},
					account ${types.text("account")},
					action ${types.text("action")} NOT NULL,
					entity_type ${types.text("entity_type")},
					entity_id ${types.text("entity_id")},
					old_value ${types.text("old_value")},
					new_value ${types.text("new_value")},
					ip_address ${types.text("ip_address")},
					user_agent ${types.text("user_agent")},
					created ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE SET NULL,
					FOREIGN KEY (account) REFERENCES accounts(username) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_project ON audit_log(project)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_account ON audit_log(account)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created)`,
		`CREATE TABLE IF NOT EXISTS customers(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					name ${types.text("name")},
					email ${types.text("email")} NOT NULL,
					phone ${types.text("phone")},
					address_line1 ${types.text("address_line1")},
					address_line2 ${types.text("address_line2")},
					city ${types.text("city")},
					state ${types.text("state")},
					postal_code ${types.text("postal_code")},
					country ${types.text("country")},
					vat_number ${types.text("vat_number")},
					tax_number ${types.text("tax_number")},
					metadata ${types.text("metadata")},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					customer_type ${types.text("customer_type")},
					vat_valid ${types.flag} CHECK (vat_valid IN (0, 1)),
					vat_checked_at ${types.int64},
					vat_checked_name ${types.text("vat_checked_name")},
					vat_checked_address ${types.text("vat_checked_address")},
					vat_check_reference ${types.text("vat_check_reference")},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					UNIQUE(project, email)
				)`,
		`CREATE INDEX IF NOT EXISTS idx_customers_project ON customers(project)`,
		`CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email)`,
		`CREATE TABLE IF NOT EXISTS customer_accounts(
					email ${types.text("email")} PRIMARY KEY,
					created ${types.int64} NOT NULL,
					accessed ${types.int64} NOT NULL
				)`,
		`CREATE TABLE IF NOT EXISTS customer_login_links(
					token_hash ${types.text("token_hash")} PRIMARY KEY,
					email ${types.text("email")} NOT NULL,
					created ${types.int64} NOT NULL,
					expires_at ${types.int64} NOT NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_customer_login_links_email ON customer_login_links(email, created)`,
		`CREATE INDEX IF NOT EXISTS idx_customer_login_links_expiry ON customer_login_links(expires_at)`,
		`CREATE TABLE IF NOT EXISTS catalog_items(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					name ${types.text("name")} NOT NULL,
					description ${types.text("description")},
					sku ${types.text("sku")},
					unit_price ${types.int64} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					tax_rate ${types.float} NOT NULL DEFAULT 0,
					archived ${types.flag} NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					supply_type ${types.text("supply_type")} NOT NULL DEFAULT 'services',
					tax_category ${types.text("tax_category")} NOT NULL DEFAULT 'standard',
					delivers_keys ${types.flag} NOT NULL DEFAULT 0 CHECK (delivers_keys IN (0, 1)),
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE
				)`,
		`CREATE INDEX IF NOT EXISTS idx_catalog_items_project ON catalog_items(project)`,
		`CREATE TABLE IF NOT EXISTS invoices(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					customer ${types.text("customer")},
					reference ${types.text("reference")} NOT NULL,
					status ${types.text("status")} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					subtotal ${types.int64} NOT NULL,
					discount_amount ${types.int64} DEFAULT 0,
					tax_amount ${types.int64} DEFAULT 0,
					total_amount ${types.int64} NOT NULL,
					paid_amount ${types.int64} DEFAULT 0,
					refunded_amount ${types.int64} DEFAULT 0,
					notes ${types.text("notes")},
					metadata ${types.text("metadata")},
					due_date ${types.int64} NOT NULL,
					paid_date ${types.int64},
					canceled_date ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					supply_date ${types.int64},
					issued_at ${types.int64},
					tax_currency ${types.text("tax_currency")},
					tax_exchange_rate ${types.float},
					tax_rate_source ${types.text("tax_rate_source")},
					tax_rate_date ${types.int64},
					buyer_country ${types.text("buyer_country")},
					buyer_vat_number ${types.text("buyer_vat_number")},
					buyer_email ${types.text("buyer_email")},
					buyer_details ${types.text("buyer_details")},
					credited_amount ${types.int64} NOT NULL DEFAULT 0,
					source ${types.text("source")} NOT NULL DEFAULT 'invoice',
					created_by ${types.text("created_by")},
					issuer_name ${types.text("issuer_name")},
					recurring ${types.text("recurring")},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (customer) REFERENCES customers(uuid) ON DELETE SET NULL,
					UNIQUE(project, reference)
				)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_project ON invoices(project)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_customer ON invoices(customer)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_due_date ON invoices(due_date)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_issued ON invoices(project, issued_at)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_source ON invoices(project, source, created_by, issued_at)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_recurring ON invoices(recurring)`,
		`CREATE INDEX IF NOT EXISTS idx_invoices_buyer_email ON invoices(buyer_email, status, created)`,
		`CREATE TABLE IF NOT EXISTS invoice_items(
					uuid ${types.text("uuid")} PRIMARY KEY,
					invoice ${types.text("invoice")} NOT NULL,
					description ${types.text("description")} NOT NULL,
					quantity ${types.float} NOT NULL,
					unit_price ${types.int64} NOT NULL,
					tax_rate ${types.float} DEFAULT 0,
					tax_amount ${types.int64} DEFAULT 0,
					total_price ${types.int64} NOT NULL,
					metadata ${types.text("metadata")},
					sort_order INTEGER DEFAULT 0,
					item ${types.text("item")},
					tax_treatment ${types.text("tax_treatment")},
					discount_amount ${types.int64} NOT NULL DEFAULT 0,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE CASCADE,
					FOREIGN KEY (item) REFERENCES catalog_items(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON invoice_items(invoice)`,
		`CREATE INDEX IF NOT EXISTS idx_invoice_items_item ON invoice_items(item)`,
		`CREATE TABLE IF NOT EXISTS item_keys(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					item ${types.text("item")} NOT NULL,
					secret ${types.text("secret")} NOT NULL,
					sequence ${types.int64} NOT NULL DEFAULT 0,
					status ${types.text("status")} NOT NULL DEFAULT 'available',
					invoice ${types.text("invoice")},
					invoice_item ${types.text("invoice_item")},
					recipient ${types.text("recipient")},
					reserved_at ${types.int64},
					delivered_at ${types.int64},
					created ${types.int64} NOT NULL,
					created_by ${types.text("created_by")},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (item) REFERENCES catalog_items(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE SET NULL,
					FOREIGN KEY (invoice_item) REFERENCES invoice_items(uuid) ON DELETE SET NULL,
					CHECK (status IN ('available', 'reserved', 'delivered')),
					UNIQUE(item, secret)
				)`,
		`CREATE INDEX IF NOT EXISTS idx_item_keys_stock ON item_keys(item, status, sequence)`,
		`CREATE INDEX IF NOT EXISTS idx_item_keys_invoice ON item_keys(invoice, status)`,
		`CREATE INDEX IF NOT EXISTS idx_item_keys_project ON item_keys(project, status)`,
		`CREATE TABLE IF NOT EXISTS invoice_issuer_signature_versions(
					invoice ${types.text("invoice")} PRIMARY KEY,
					signature_version ${types.text("signature_version")} NOT NULL,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE CASCADE,
					FOREIGN KEY (signature_version) REFERENCES project_member_signature_versions(uuid)
				)`,
		`CREATE TABLE IF NOT EXISTS invoice_issue_snapshots(
					invoice ${types.text("invoice")} PRIMARY KEY,
					schema_version INTEGER NOT NULL,
					seller_details ${types.text("seller_details")} NOT NULL,
					document_settings ${types.text("document_settings")} NOT NULL,
					created ${types.int64} NOT NULL,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS invoice_documents(
					invoice ${types.text("invoice")} PRIMARY KEY,
					storage_key ${types.text("storage_key")} NOT NULL UNIQUE,
					content_type ${types.text("content_type")} NOT NULL,
					byte_size ${types.int64},
					sha256 ${types.text("sha256")},
					status ${types.text("status")} NOT NULL,
					attempts INTEGER NOT NULL DEFAULT 0,
					last_error ${types.text("last_error")},
					next_attempt_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE CASCADE,
					CHECK (status IN ('pending', 'ready', 'failed'))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_invoice_documents_retry ON invoice_documents(status, next_attempt_at)`,
		`CREATE TABLE IF NOT EXISTS invoice_sequences(
					project ${types.text("project")} NOT NULL,
					day ${types.text("day")} NOT NULL,
					next_number INTEGER NOT NULL,
					PRIMARY KEY (project, day),
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS credit_notes(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					invoice ${types.text("invoice")} NOT NULL,
					reference ${types.text("reference")} NOT NULL,
					reason ${types.text("reason")},
					currency ${types.text("currency")} NOT NULL,
					subtotal ${types.int64} NOT NULL,
					tax_amount ${types.int64} NOT NULL,
					total_amount ${types.int64} NOT NULL,
					transaction_id ${types.text("transaction_id")},
					issued_at ${types.int64} NOT NULL,
					created_by ${types.text("created_by")},
					created ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE CASCADE,
					UNIQUE(project, reference)
				)`,
		`CREATE INDEX IF NOT EXISTS idx_credit_notes_invoice ON credit_notes(invoice)`,
		`CREATE INDEX IF NOT EXISTS idx_credit_notes_issued ON credit_notes(project, issued_at)`,
		`CREATE TABLE IF NOT EXISTS credit_note_items(
					uuid ${types.text("uuid")} PRIMARY KEY,
					credit_note ${types.text("credit_note")} NOT NULL,
					invoice_item ${types.text("invoice_item")},
					description ${types.text("description")} NOT NULL,
					tax_rate ${types.float} NOT NULL DEFAULT 0,
					tax_treatment ${types.text("tax_treatment")},
					net_amount ${types.int64} NOT NULL,
					tax_amount ${types.int64} NOT NULL,
					sort_order INTEGER NOT NULL DEFAULT 0,
					FOREIGN KEY (credit_note) REFERENCES credit_notes(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice_item) REFERENCES invoice_items(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_credit_note_items_note ON credit_note_items(credit_note)`,
		`CREATE INDEX IF NOT EXISTS idx_credit_note_items_line ON credit_note_items(invoice_item)`,
		`CREATE TABLE IF NOT EXISTS credit_note_issue_snapshots(
					credit_note ${types.text("credit_note")} PRIMARY KEY,
					schema_version INTEGER NOT NULL,
					seller_details ${types.text("seller_details")} NOT NULL,
					document_settings ${types.text("document_settings")} NOT NULL,
					created ${types.int64} NOT NULL,
					FOREIGN KEY (credit_note) REFERENCES credit_notes(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS credit_note_documents(
					credit_note ${types.text("credit_note")} PRIMARY KEY,
					storage_key ${types.text("storage_key")} NOT NULL UNIQUE,
					content_type ${types.text("content_type")} NOT NULL,
					byte_size ${types.int64},
					sha256 ${types.text("sha256")},
					status ${types.text("status")} NOT NULL,
					attempts INTEGER NOT NULL DEFAULT 0,
					last_error ${types.text("last_error")},
					next_attempt_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (credit_note) REFERENCES credit_notes(uuid) ON DELETE CASCADE,
					CHECK (status IN ('pending', 'ready', 'failed'))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_credit_note_documents_retry ON credit_note_documents(status, next_attempt_at)`,
		`CREATE TABLE IF NOT EXISTS transactions(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					invoice ${types.text("invoice")},
					customer ${types.text("customer")},
					processor ${types.text("processor")} NOT NULL,
					processor_tx_id ${types.text("processor_tx_id")},
					status ${types.text("status")} NOT NULL,
					type ${types.text("type")} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					amount ${types.int64} NOT NULL,
					fee_amount ${types.int64} DEFAULT 0,
					net_amount ${types.int64},
					risk_score INTEGER,
					exchange_rate ${types.float},
					payment_method ${types.text("payment_method")},
					payment_details ${types.text("payment_details")},
					error_code ${types.text("error_code")},
					error_message ${types.text("error_message")},
					confirmations INTEGER,
					confirmed_at ${types.int64},
					completed_at ${types.int64},
					failed_at ${types.int64},
					expires_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					parent_transaction ${types.text("parent_transaction")},
					license_billing ${types.text("license_billing")},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE SET NULL,
					FOREIGN KEY (customer) REFERENCES customers(uuid) ON DELETE SET NULL,
					FOREIGN KEY (parent_transaction) REFERENCES transactions(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_tx_project ON transactions(project)`,
		`CREATE INDEX IF NOT EXISTS idx_tx_invoice ON transactions(invoice)`,
		`CREATE INDEX IF NOT EXISTS idx_tx_processor ON transactions(processor)`,
		`CREATE INDEX IF NOT EXISTS idx_tx_status ON transactions(status)`,
		`CREATE INDEX IF NOT EXISTS idx_tx_created ON transactions(created)`,
		`CREATE INDEX IF NOT EXISTS idx_tx_parent ON transactions(parent_transaction)`,
		`CREATE INDEX IF NOT EXISTS idx_tx_license_billing ON transactions(project, license_billing)`,
		`CREATE TABLE IF NOT EXISTS refunds(
					uuid ${types.text("uuid")} PRIMARY KEY,
					transaction_id ${types.text("transaction_id")} NOT NULL,
					processor_refund_id ${types.text("processor_refund_id")},
					amount ${types.int64} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					reason ${types.text("reason")},
					status ${types.text("status")} NOT NULL,
					metadata ${types.text("metadata")},
					initiated_by ${types.text("initiated_by")},
					created ${types.int64} NOT NULL,
					completed_at ${types.int64},
					FOREIGN KEY (transaction_id) REFERENCES transactions(uuid) ON DELETE CASCADE,
					FOREIGN KEY (initiated_by) REFERENCES accounts(username) ON DELETE SET NULL
				)`,
		`CREATE TABLE IF NOT EXISTS payment_methods(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					processor ${types.text("processor")} NOT NULL,
					enabled ${types.flag} DEFAULT 1 CHECK (enabled IN (0, 1)),
					config ${types.text("config")},
					fee_type ${types.text("fee_type")},
					fee_config ${types.text("fee_config")},
					min_amount ${types.int64},
					max_amount ${types.int64},
					allowed_currencies ${types.text("allowed_currencies")},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					UNIQUE(project, processor)
				)`,
		`CREATE TABLE IF NOT EXISTS crypto_addresses(
					address ${types.text("address")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					derivation_index INTEGER NOT NULL,
					wallet_key ${types.text("wallet_key")},
					wallet_account INTEGER,
					invoice ${types.text("invoice")},
					transaction_id ${types.text("transaction_id")},
					label ${types.text("label")},
					monitored ${types.flag} DEFAULT 1 CHECK (monitored IN (0, 1)),
					balance ${types.int64} DEFAULT 0,
					total_received ${types.int64} DEFAULT 0,
					last_checked ${types.int64},
					created ${types.int64} NOT NULL,
					expires_at ${types.int64},
					expected_amount ${types.int64},
					exchange_rate ${types.float},
					invoice_currency ${types.text("invoice_currency")},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE SET NULL,
					FOREIGN KEY (transaction_id) REFERENCES transactions(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_crypto_project ON crypto_addresses(project)`,
		`CREATE INDEX IF NOT EXISTS idx_crypto_invoice ON crypto_addresses(invoice)`,
		`CREATE INDEX IF NOT EXISTS idx_crypto_monitored ON crypto_addresses(monitored)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_crypto_derivation ON crypto_addresses(project, currency, derivation_index)`,
		`CREATE INDEX IF NOT EXISTS idx_crypto_addresses_wallet ON crypto_addresses(wallet_key, currency, derivation_index)`,
		`CREATE TABLE IF NOT EXISTS payment_sessions(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					invoice ${types.text("invoice")},
					customer_email ${types.text("customer_email")},
					processor ${types.text("processor")} NOT NULL,
					processor_session_id ${types.text("processor_session_id")},
					amount ${types.int64} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					status ${types.text("status")} NOT NULL,
					return_url ${types.text("return_url")},
					cancel_url ${types.text("cancel_url")},
					metadata ${types.text("metadata")},
					ip_address ${types.text("ip_address")},
					user_agent ${types.text("user_agent")},
					created ${types.int64} NOT NULL,
					expires_at ${types.int64} NOT NULL,
					completed_at ${types.int64},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_session_status ON payment_sessions(status)`,
		`CREATE INDEX IF NOT EXISTS idx_session_expires ON payment_sessions(expires_at)`,
		`CREATE TABLE IF NOT EXISTS webhook_events(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					processor ${types.text("processor")} NOT NULL,
					event_type ${types.text("event_type")} NOT NULL,
					event_id ${types.text("event_id")},
					transaction_id ${types.text("transaction_id")},
					payload ${types.text("payload")} NOT NULL,
					headers ${types.text("headers")},
					signature ${types.text("signature")},
					verified ${types.flag} DEFAULT 0 CHECK (verified IN (0, 1)),
					processed ${types.flag} DEFAULT 0 CHECK (processed IN (0, 1)),
					attempts INTEGER DEFAULT 0,
					error_message ${types.text("error_message")},
					received_at ${types.int64} NOT NULL,
					processed_at ${types.int64},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (transaction_id) REFERENCES transactions(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_webhook_project ON webhook_events(project)`,
		`CREATE INDEX IF NOT EXISTS idx_webhook_processed ON webhook_events(processed)`,
		`CREATE TABLE IF NOT EXISTS webhook_deliveries(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					event_type ${types.text("event_type")} NOT NULL,
					target_url ${types.text("target_url")} NOT NULL,
					payload ${types.text("payload")} NOT NULL,
					status ${types.text("status")} NOT NULL,
					attempts INTEGER DEFAULT 0,
					response_status INTEGER,
					last_error ${types.text("last_error")},
					next_attempt_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					delivered_at ${types.int64},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE
				)`,
		`CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_pending ON webhook_deliveries(status, next_attempt_at)`,
		`CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_project ON webhook_deliveries(project)`,
		`CREATE TABLE IF NOT EXISTS discounts(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					code ${types.text("code")} NOT NULL,
					type ${types.text("type")} NOT NULL,
					value ${types.int64} NOT NULL,
					max_uses ${types.int64},
					used_count ${types.int64} DEFAULT 0,
					valid_from ${types.int64},
					valid_until ${types.int64},
					created ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					UNIQUE(project, code)
				)`,
		`CREATE TABLE IF NOT EXISTS tax_rates(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					name ${types.text("name")} NOT NULL,
					rate ${types.float} NOT NULL,
					jurisdiction ${types.text("jurisdiction")},
					is_compound ${types.flag} DEFAULT 0 CHECK (is_compound IN (0, 1)),
					is_default ${types.flag} DEFAULT 0 CHECK (is_default IN (0, 1)),
					created ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS email_messages(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					invoice ${types.text("invoice")},
					member ${types.text("member")},
					kind ${types.text("kind")} NOT NULL,
					recipient ${types.text("recipient")} NOT NULL,
					reply_to ${types.text("reply_to")},
					sender_name ${types.text("sender_name")} NOT NULL,
					subject ${types.text("subject")} NOT NULL,
					body_text ${types.text("body_text")} NOT NULL,
					body_html ${types.text("body_html")} NOT NULL,
					attachment_name ${types.text("attachment_name")},
					attachment_data ${types.text("attachment_data")},
					attachment_storage_key ${types.text("attachment_storage_key")},
					status ${types.text("status")} NOT NULL DEFAULT 'pending',
					attempts INTEGER NOT NULL DEFAULT 0,
					last_error ${types.text("last_error")},
					next_attempt_at ${types.int64},
					sent_by ${types.text("sent_by")},
					sent_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_email_messages_queue ON email_messages(status, next_attempt_at)`,
		`CREATE INDEX IF NOT EXISTS idx_email_messages_invoice ON email_messages(invoice, kind)`,
		`CREATE TABLE IF NOT EXISTS recurring_invoices(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					customer ${types.text("customer")} NOT NULL,
					title ${types.text("title")},
					currency ${types.text("currency")} NOT NULL,
					discount_amount ${types.int64} NOT NULL DEFAULT 0,
					notes ${types.text("notes")},
					interval_unit ${types.text("interval_unit")} NOT NULL,
					interval_count INTEGER NOT NULL DEFAULT 1,
					start_date ${types.int64} NOT NULL,
					anchor_date ${types.int64} NOT NULL,
					anchor_occurrence INTEGER NOT NULL DEFAULT 0,
					next_run_at ${types.int64},
					occurrences INTEGER NOT NULL DEFAULT 0,
					max_occurrences INTEGER,
					end_date ${types.int64},
					days_until_due INTEGER NOT NULL DEFAULT 14,
					auto_issue ${types.flag} NOT NULL DEFAULT 1 CHECK (auto_issue IN (0, 1)),
					auto_send ${types.flag} NOT NULL DEFAULT 1 CHECK (auto_send IN (0, 1)),
					status ${types.text("status")} NOT NULL DEFAULT 'active',
					failures INTEGER NOT NULL DEFAULT 0,
					last_invoice ${types.text("last_invoice")},
					last_run_at ${types.int64},
					last_error ${types.text("last_error")},
					created_by ${types.text("created_by")},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (customer) REFERENCES customers(uuid),
					FOREIGN KEY (last_invoice) REFERENCES invoices(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_recurring_due ON recurring_invoices(status, next_run_at)`,
		`CREATE INDEX IF NOT EXISTS idx_recurring_project ON recurring_invoices(project)`,
		`CREATE INDEX IF NOT EXISTS idx_recurring_customer ON recurring_invoices(customer)`,
		`CREATE TABLE IF NOT EXISTS recurring_invoice_items(
					uuid ${types.text("uuid")} PRIMARY KEY,
					recurring ${types.text("recurring")} NOT NULL,
					description ${types.text("description")} NOT NULL,
					quantity ${types.float} NOT NULL,
					unit_price ${types.int64} NOT NULL,
					tax_rate ${types.float} NOT NULL DEFAULT 0,
					item ${types.text("item")},
					tax_treatment ${types.text("tax_treatment")},
					sort_order INTEGER NOT NULL DEFAULT 0,
					FOREIGN KEY (recurring) REFERENCES recurring_invoices(uuid) ON DELETE CASCADE,
					FOREIGN KEY (item) REFERENCES catalog_items(uuid) ON DELETE SET NULL
				)`,
		`CREATE INDEX IF NOT EXISTS idx_recurring_items ON recurring_invoice_items(recurring)`,
		`CREATE TABLE IF NOT EXISTS recurring_expenses(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					description ${types.text("description")} NOT NULL,
					supplier ${types.text("supplier")},
					supplier_tax_number ${types.text("supplier_tax_number")},
					supplier_country ${types.text("supplier_country")},
					category ${types.text("category")} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					total_amount ${types.int64} NOT NULL,
					tax_amount ${types.int64} NOT NULL,
					deductible_tax_amount ${types.int64} NOT NULL,
					vat_treatment ${types.text("vat_treatment")} NOT NULL DEFAULT 'not_reported',
					asset_type ${types.text("asset_type")} NOT NULL DEFAULT 'expense',
					notes ${types.text("notes")},
					interval_unit ${types.text("interval_unit")} NOT NULL,
					interval_count INTEGER NOT NULL,
					anchor_date ${types.int64} NOT NULL,
					anchor_occurrence INTEGER NOT NULL DEFAULT 0,
					occurrences INTEGER NOT NULL DEFAULT 0,
					next_run_at ${types.int64},
					end_date ${types.int64},
					max_occurrences INTEGER,
					auto_paid ${types.flag} NOT NULL DEFAULT 0 CHECK (auto_paid IN (0, 1)),
					status ${types.text("status")} NOT NULL DEFAULT 'active',
					created_by ${types.text("created_by")},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					CHECK (status IN ('active', 'paused', 'completed', 'canceled')),
					CHECK (vat_treatment IN ('not_reported', 'domestic', 'domestic_reverse_charge', 'eu_goods', 'eu_services', 'import', 'exempt')),
					CHECK (asset_type IN ('expense', 'real_estate', 'fixed_asset'))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_recurring_expenses_due ON recurring_expenses(status, next_run_at)`,
		`CREATE TABLE IF NOT EXISTS expenses(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					description ${types.text("description")} NOT NULL,
					supplier ${types.text("supplier")},
					supplier_tax_number ${types.text("supplier_tax_number")},
					supplier_country ${types.text("supplier_country")},
					invoice_number ${types.text("invoice_number")},
					category ${types.text("category")} NOT NULL,
					currency ${types.text("currency")} NOT NULL,
					total_amount ${types.int64} NOT NULL,
					tax_amount ${types.int64} NOT NULL,
					deductible_tax_amount ${types.int64} NOT NULL,
					expense_date ${types.int64} NOT NULL,
					issue_date ${types.int64},
					receipt_date ${types.int64},
					supply_date ${types.int64},
					vat_treatment ${types.text("vat_treatment")} NOT NULL DEFAULT 'not_reported',
					asset_type ${types.text("asset_type")} NOT NULL DEFAULT 'expense',
					vat_handling ${types.text("vat_handling")} NOT NULL DEFAULT '1',
					self_assessment_period ${types.text("self_assessment_period")},
					self_assessment_tax ${types.int64},
					tax_exchange_rate ${types.float},
					tax_rate_date ${types.int64},
					paid_at ${types.int64},
					notes ${types.text("notes")},
					recurring ${types.text("recurring")},
					occurrence INTEGER,
					created_by ${types.text("created_by")},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (recurring) REFERENCES recurring_expenses(uuid),
					UNIQUE(recurring, occurrence),
					CHECK (total_amount > 0 AND tax_amount >= 0 AND tax_amount <= total_amount),
					CHECK (deductible_tax_amount >= 0 AND deductible_tax_amount <= tax_amount),
					CHECK (vat_treatment IN ('not_reported', 'domestic', 'domestic_reverse_charge', 'eu_goods', 'eu_services', 'import', 'exempt')),
					CHECK (asset_type IN ('expense', 'real_estate', 'fixed_asset')),
					CHECK (vat_handling IN ('1', '2', '3'))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_expenses_project_date ON expenses(project, expense_date)`,
		`CREATE INDEX IF NOT EXISTS idx_expenses_project_paid ON expenses(project, paid_at)`,
		`CREATE TABLE IF NOT EXISTS expense_vat_lines(
					uuid ${types.text("uuid")} PRIMARY KEY,
					expense ${types.text("expense")} NOT NULL,
					rate ${types.float} NOT NULL,
					tax_base ${types.int64} NOT NULL,
					tax_amount ${types.int64} NOT NULL,
					deductible_tax_amount ${types.int64} NOT NULL,
					sort_order INTEGER NOT NULL,
					FOREIGN KEY (expense) REFERENCES expenses(uuid) ON DELETE CASCADE,
					CHECK (rate >= 0 AND tax_base >= 0 AND tax_amount >= 0 AND deductible_tax_amount >= 0 AND deductible_tax_amount <= tax_amount)
				)`,
		`CREATE INDEX IF NOT EXISTS idx_expense_vat_lines_expense ON expense_vat_lines(expense, sort_order)`,
		`CREATE TABLE IF NOT EXISTS expense_attachments(
					expense ${types.text("expense")} PRIMARY KEY,
					storage_key ${types.text("storage_key")} NOT NULL UNIQUE,
					file_name ${types.text("file_name")} NOT NULL,
					content_type ${types.text("content_type")} NOT NULL,
					byte_size ${types.int64} NOT NULL,
					sha256 ${types.text("sha256")} NOT NULL,
					created ${types.int64} NOT NULL,
					FOREIGN KEY (expense) REFERENCES expenses(uuid) ON DELETE CASCADE
				)`,
		`CREATE TABLE IF NOT EXISTS ddv_exports(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					period_from ${types.int64} NOT NULL,
					period_to ${types.int64} NOT NULL,
					revision INTEGER NOT NULL,
					file_name ${types.text("file_name")} NOT NULL,
					storage_key ${types.text("storage_key")} NOT NULL UNIQUE,
					byte_size ${types.int64} NOT NULL,
					sha256 ${types.text("sha256")} NOT NULL,
					created_by ${types.text("created_by")},
					created ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					UNIQUE(project, period_from, period_to, revision)
				)`,
		`CREATE INDEX IF NOT EXISTS idx_ddv_exports_period ON ddv_exports(project, period_from, period_to, revision)`,
		`CREATE TABLE IF NOT EXISTS accounting_period_locks(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					period_from ${types.int64} NOT NULL,
					period_to ${types.int64} NOT NULL,
					timezone ${types.text("timezone")} NOT NULL,
					source ${types.text("source")} NOT NULL,
					source_id ${types.text("source_id")} NOT NULL,
					locked_by ${types.text("locked_by")},
					locked_at ${types.int64} NOT NULL,
					unlocked_by ${types.text("unlocked_by")},
					unlocked_at ${types.int64},
					unlock_reason ${types.text("unlock_reason")},
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (source_id) REFERENCES ddv_exports(uuid) ON DELETE CASCADE,
					CHECK (period_to >= period_from),
					CHECK (source IN ('ddv_export'))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_accounting_locks_active ON accounting_period_locks(project, unlocked_at, period_from, period_to)`,
		`CREATE INDEX IF NOT EXISTS idx_accounting_locks_source ON accounting_period_locks(source_id)`,
		`CREATE TABLE IF NOT EXISTS report_snapshots(
					project ${types.text("project")} NOT NULL,
					kind ${types.text("kind")} NOT NULL,
					data ${types.text("data")},
					generated_at ${types.int64},
					claim_token ${types.text("claim_token")},
					claimed_at ${types.int64},
					PRIMARY KEY(project, kind),
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					CHECK (kind IN ('financial', 'vat', 'items'))
				)`,
		`CREATE TABLE IF NOT EXISTS license_keys(
					uuid ${types.text("uuid")} PRIMARY KEY,
					code ${types.text("code")} NOT NULL UNIQUE,
					type ${types.text("type")} NOT NULL,
					transactions INTEGER,
					duration_days INTEGER,
					storage_gb INTEGER,
					status ${types.text("status")} NOT NULL DEFAULT 'available',
					price ${types.int64},
					currency ${types.text("currency")},
					buyer_name ${types.text("buyer_name")},
					buyer_email ${types.text("buyer_email")},
					note ${types.text("note")},
					created_by ${types.text("created_by")},
					redeemed_project ${types.text("redeemed_project")},
					redeemed_by ${types.text("redeemed_by")},
					redeemed_at ${types.int64},
					revoked_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (redeemed_project) REFERENCES projects(uuid) ON DELETE SET NULL,
					CHECK (type IN ('transactions', 'white_label', 'storage')),
					CHECK (status IN ('available', 'redeemed', 'revoked'))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_license_keys_status ON license_keys(status, created)`,
		`CREATE INDEX IF NOT EXISTS idx_license_keys_project ON license_keys(redeemed_project)`,
		`CREATE TABLE IF NOT EXISTS fiscal_settings(
					project ${types.text("project")} PRIMARY KEY,
					environment ${types.text("environment")} NOT NULL DEFAULT 'test',
					certificate ${types.text("certificate")},
					certificate_holder ${types.text("certificate_holder")},
					certificate_tax_number INTEGER,
					certificate_serial ${types.text("certificate_serial")},
					certificate_valid_to ${types.int64},
					enabled ${types.flag} NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
					online_premise ${types.text("online_premise")},
					online_device ${types.text("online_device")},
					pos_premise ${types.text("pos_premise")},
					pos_device ${types.text("pos_device")},
					operator_tax_number INTEGER,
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					CHECK (environment IN ('test', 'production'))
				)`,
		`CREATE TABLE IF NOT EXISTS fiscal_premises(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					environment ${types.text("environment")} NOT NULL,
					premise_id ${types.text("premise_id")} NOT NULL,
					kind ${types.text("kind")} NOT NULL,
					premise_type ${types.text("premise_type")},
					cadastral_number INTEGER,
					building_number INTEGER,
					building_section_number INTEGER,
					street ${types.text("street")},
					house_number ${types.text("house_number")},
					house_number_additional ${types.text("house_number_additional")},
					community ${types.text("community")},
					city ${types.text("city")},
					postal_code ${types.text("postal_code")},
					validity_date ${types.text("validity_date")} NOT NULL,
					registered_at ${types.int64} NOT NULL,
					closed_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					UNIQUE(project, environment, premise_id),
					CHECK (kind IN ('real_estate', 'movable')),
					CHECK (environment IN ('test', 'production'))
				)`,
		`CREATE TABLE IF NOT EXISTS fiscal_documents(
					uuid ${types.text("uuid")} PRIMARY KEY,
					project ${types.text("project")} NOT NULL,
					invoice ${types.text("invoice")},
					credit_note ${types.text("credit_note")},
					environment ${types.text("environment")} NOT NULL,
					premise_id ${types.text("premise_id")} NOT NULL,
					device_id ${types.text("device_id")} NOT NULL,
					invoice_number ${types.text("invoice_number")} NOT NULL,
					issued_at ${types.int64} NOT NULL,
					tax_number INTEGER NOT NULL,
					amount ${types.int64} NOT NULL,
					zoi ${types.text("zoi")} NOT NULL,
					eor ${types.text("eor")},
					status ${types.text("status")} NOT NULL DEFAULT 'pending',
					payload ${types.text("payload")} NOT NULL,
					attempts INTEGER NOT NULL DEFAULT 0,
					subsequent ${types.flag} NOT NULL DEFAULT 0 CHECK (subsequent IN (0, 1)),
					next_attempt_at ${types.int64},
					deadline ${types.int64} NOT NULL,
					error_code ${types.text("error_code")},
					last_error ${types.text("last_error")},
					message_id ${types.text("message_id")},
					operator_name ${types.text("operator_name")},
					operator_tax_number INTEGER,
					verified_at ${types.int64},
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					FOREIGN KEY (invoice) REFERENCES invoices(uuid) ON DELETE CASCADE,
					FOREIGN KEY (credit_note) REFERENCES credit_notes(uuid) ON DELETE CASCADE,
					UNIQUE(invoice),
					UNIQUE(credit_note),
					CHECK (status IN ('pending', 'verified', 'rejected')),
					CHECK ((invoice IS NULL) <> (credit_note IS NULL))
				)`,
		`CREATE INDEX IF NOT EXISTS idx_fiscal_documents_due ON fiscal_documents(status, next_attempt_at)`,
		`CREATE INDEX IF NOT EXISTS idx_fiscal_documents_project ON fiscal_documents(project, created)`,
		`CREATE TABLE IF NOT EXISTS fiscal_operators(
					project ${types.text("project")} NOT NULL,
					username ${types.text("username")} NOT NULL,
					tax_number INTEGER NOT NULL,
					created ${types.int64} NOT NULL,
					updated ${types.int64} NOT NULL,
					PRIMARY KEY (project, username),
					FOREIGN KEY (project) REFERENCES projects(uuid) ON DELETE CASCADE,
					CHECK (tax_number BETWEEN 10000000 AND 99999999)
				)`,
	]);
}
