export enum Error {
	DDV_EXPORT_NOT_FOUND = 1124,
	DDV_EVIDENCE_INVALID = 1123,
	INVALID_DDV_PERIOD = 1125,
	STORAGE_LIMIT_REACHED = 1126,
	INVALID_TIMEZONE = 1127,
	ACCOUNTING_PERIOD_LOCKED = 1128,
	ACCOUNTING_PERIOD_LOCK_NOT_FOUND = 1129,
	INVALID_UNLOCK_REASON = 1130,
	ACCOUNTING_TIMEZONE_LOCKED = 1131,
	INVOICE_DATA_INCOMPLETE = 1132,
	TWO_FACTOR_REQUIRED = 1133,
	INVALID_TWO_FACTOR_CODE = 1134,
	TWO_FACTOR_ALREADY_ENABLED = 1135,
	TWO_FACTOR_NOT_ENABLED = 1136,
	TWO_FACTOR_SETUP_EXPIRED = 1137,
	FISCAL_CERTIFICATE_INVALID = 1138,
	FISCAL_CERTIFICATE_REJECTED = 1139,
	FISCAL_NOT_CONFIGURED = 1140,
	FISCAL_INVALID_PREMISE = 1141,
	FURS_UNAVAILABLE = 1142,
	FURS_REJECTED = 1143,
	FISCAL_DOCUMENT_NOT_FOUND = 1144,
	FISCAL_CERTIFICATE_REQUIRED = 1145,
	FISCAL_PREMISE_NOT_REGISTERED = 1146,
	BACKUPS_UNSUPPORTED = 1147,
	BACKUP_FAILED = 1148,
	BACKUP_IN_PROGRESS = 1149,
	STORE_LICENSE_REQUIRED = 1150,
	INVALID_STORE_SETTINGS = 1151,
	STORE_SLUG_TAKEN = 1152,
	STORE_NOT_FOUND = 1153,
	INVALID_STORE_CATEGORY = 1154,
	STORE_CATEGORY_NOT_FOUND = 1155,
	INVALID_STORE_PRODUCT = 1156,
	STORE_PRODUCT_NOT_FOUND = 1157,
	INVALID_STORE_IMAGE = 1158,
	STORE_IMAGE_NOT_FOUND = 1159,
	STORE_IMAGE_LIMIT = 1160,
	INVALID_CART = 1161,
	STORE_OUT_OF_STOCK = 1162,
	STORE_ORDER_NOT_FOUND = 1163,
	INVALID_STORE_ORDER = 1164,
	STORE_DOMAIN_TAKEN = 1165,
	INVALID_CUSTOMER_PROFILE = 1166,
	CHECKOUT_TERMS_REQUIRED = 1167,
	STORE_CHECKOUT_UNAVAILABLE = 1168,
	CHECKOUT_WAIVER_REQUIRED = 1169,
	INVALID_INVOICE_DESIGN = 1170,
	INVALID_EMAIL_DESIGN = 1171,
	ESLOG_DATA_INCOMPLETE = 1172,
	INVALID_REFERENCE_DOCUMENT = 1173,
	INVALID_CUSTOMER_BANK_ACCOUNT = 1174,
	SIGNING_CERTIFICATE_INVALID = 1175,
	SIGNING_CERTIFICATE_REJECTED = 1176,
	ESLOG_ARCHIVE_DAMAGED = 1177,
	ESLOG_VERSION_NOT_FOUND = 1178,
	ESLOG_UNAVAILABLE = 1179,
	INVALID_EINVOICE = 1180,
	EXPENSE_ALREADY_IMPORTED = 1181,
	REGISTRATIONS_CLOSED = 1182,
	INVITE_CODE_REQUIRED = 1183,
	INVALID_INVITE_CODE = 1184,
	REGISTRATION_LIMIT_REACHED = 1185,
	INVITE_NOT_FOUND = 1186,
	INVALID_INVITE = 1187,
	INVITE_NOT_REVOCABLE = 1188,
	WORKFORCE_LICENSE_REQUIRED = 1189,
	INVALID_TIME_ENTRY = 1190,
	TIME_ENTRY_NOT_FOUND = 1191,
	TIME_ENTRY_OVERLAPS = 1192,
	TIMESHEET_LOCKED = 1193,
	INVALID_ABSENCE = 1194,
	ABSENCE_NOT_FOUND = 1195,
	ABSENCE_ALREADY_DECIDED = 1196,
	INVALID_WORKFORCE_SETTINGS = 1197,
	INVALID_HOLIDAY = 1198,
	HOLIDAY_NOT_FOUND = 1199,
	HOLIDAY_EXISTS = 1200,
	INVALID_TICKET = 1201,
	TICKET_NOT_FOUND = 1202,
	INVALID_TICKET_COMMENT = 1203,
	TICKET_COMMENT_NOT_FOUND = 1204,
	TICKET_ACCESS_DENIED = 1205,
	NOTHING_TO_INVOICE = 1206,
	INVALID_EMPLOYEE = 1207,
	EMPLOYEE_NOT_FOUND = 1208,
	TIME_ENTRY_INVOICED = 1209,
	INVALID_LEAVE_BALANCE = 1210,
	TICKET_RATE_MISSING = 1211,
	ABSENCE_OVERLAPS = 1212,
	INVALID_PAYROLL_RATES = 1213,
	PAYROLL_RATES_NOT_FOUND = 1214,
	PAYROLL_RATES_UNVERIFIED = 1215,
	PAYROLL_RUN_NOT_FOUND = 1216,
	PAYROLL_RUN_EXISTS = 1217,
	PAYROLL_RUN_FINAL = 1218,
	INVALID_PAYROLL_RUN = 1219,
	INVALID_PAYROLL_ITEMS = 1220,
	PAYROLL_LINE_NOT_FOUND = 1221,
	REK_DATA_INCOMPLETE = 1222,
	SEPA_DATA_INCOMPLETE = 1223,
	PAYROLL_RUN_NOT_FINAL = 1224,
	INVALID_COUPON = 1225,
	COUPON_USED_UP = 1226,
	INVALID_STORE_COUPON = 1227,
	STORE_COUPON_NOT_FOUND = 1228,
	STORE_COUPON_EXISTS = 1229,
	SECURITY_KEY_NOT_FOUND = 1230,
	INVALID_SECURITY_KEY = 1231,
	SECURITY_KEY_LIMIT = 1232,
	INVALID_SECURITY_KEY_NAME = 1233,
	TERMS_NOT_ACCEPTED = 1234,
	LEGAL_DOCUMENTS_CHANGED = 1235,
	INVALID_LEGAL_DOCUMENT = 1236,
	LEGAL_DOCUMENT_NOT_FOUND = 1237,
	INVALID_EFFECTIVE_DATE = 1238,
	ACCOUNT_OWNS_SHARED_PROJECTS = 1239,
	LICENSE_ISSUER_ONLY = 1240,
	LICENSE_OTHER_SERVER = 1241,
	SIGNED_LICENSE_REQUIRED = 1242,
	EMPLOYEE_SEATS_EXCEEDED = 1243,
	INVALID_EXPENSE_ATTACHMENT = 1121,
	EXPENSE_ATTACHMENT_NOT_FOUND = 1122,
	INVALID_MEMBER_PROFILE = 1120,
	REPORT_COOLDOWN = 1117,
	REPORT_GENERATING = 1118,
	REPORT_NOT_GENERATED = 1119,
	EXPENSE_SCHEDULE_CHANGED = 1116,
	INVALID_EXPENSE = 1112,
	EXPENSE_NOT_FOUND = 1113,
	EXPENSE_SCHEDULE_NOT_FOUND = 1114,
	EXPENSE_SCHEDULE_CLOSED = 1115,
	SUCCESS = 0,
	INVALID_ENDPOINT = 404,
	METHOD_NOT_ALLOWED = 405,
	BEARER_TOKEN_MISSING = 1000,
	REQUIRED_DATA_MISSING = 1001,
	INVALID_PROJECT_NAME = 1002,
	INVALID_USERNAME_FORMAT = 1003,
	PASSWORD_NOT_HASHED = 1004,
	PROJECT_ALREADY_EXISTS = 1005,
	INVALID_PROJECT = 1006,
	USERNAME_OR_EMAIL_ALREADY_EXISTS = 1007,
	INVALID_API_SECRET_KEY = 1008,
	INVALID_EMAIL = 1009,
	INVALID_TRANSACTION_ID = 1010,
	MISSING_AUTHORIZATION_HEADER = 1011,
	INVALID_USERNAME = 1012,
	INVALID_PASSWORD = 1013,
	INCORRECT_PASSWORD = 1014,
	REDIS_CONNECTION_ERROR = 1015,
	INVALID_TOKEN = 1016,
	TOKEN_EXPIRED = 1017,
	MISSING_USERNAME_AND_TOKEN = 1018,
	PROJECT_NOT_FOUND = 1019,
	NOT_PROJECT_MEMBER = 1020,
	MEMBER_NOT_FOUND = 1021,
	MEMBER_ALREADY_EXISTS = 1022,
	INVALID_ROLE = 1023,
	CANNOT_DEMOTE_LAST_OWNER = 1024,
	CANNOT_MODIFY_OWN_MEMBERSHIP = 1025,
	ACCOUNT_SUSPENDED = 1026,
	INVALID_MEMBER_ID = 1027,
	MASTER_KEY_NOT_CONFIGURED = 1028,
	INVALID_WEBHOOK_URL = 1029,
	RATE_LIMITED = 1030,
	CUSTOMER_NOT_FOUND = 1031,
	CUSTOMER_ALREADY_EXISTS = 1032,
	INVALID_CUSTOMER_ID = 1033,
	INVALID_COUNTRY_CODE = 1034,
	INVOICE_NOT_FOUND = 1035,
	INVALID_INVOICE_ID = 1036,
	INVALID_CURRENCY = 1037,
	INVALID_INVOICE_ITEMS = 1038,
	INVALID_INVOICE_AMOUNT = 1039,
	INVALID_DUE_DATE = 1040,
	INVOICE_NOT_EDITABLE = 1041,
	INVOICE_ALREADY_CANCELED = 1042,
	INVOICE_ALREADY_PAID = 1043,
	INVALID_INVOICE_STATUS = 1044,
	CUSTOMER_HAS_INVOICES = 1045,
	TRANSACTION_NOT_FOUND = 1046,
	INVALID_TRANSACTION_AMOUNT = 1047,
	INVALID_PROCESSOR = 1048,
	CURRENCY_MISMATCH = 1049,
	INVOICE_NOT_PAYABLE = 1050,
	REFUND_EXCEEDS_PAID = 1051,
	TRANSACTION_NOT_REFUNDABLE = 1052,
	INVALID_TRANSACTION_STATUS = 1053,
	PROCESSOR_DISABLED = 1054,
	INVALID_EXCHANGE_RATE = 1055,
	CURRENCY_NOT_SUPPORTED = 1056,
	INVALID_WEBHOOK_SIGNATURE = 1057,
	PROCESSOR_UNAVAILABLE = 1058,
	RATE_UNAVAILABLE = 1059,
	INVALID_DATE_FORMAT = 1060,
	INVALID_SUPPLY_DATE = 1061,
	INVALID_LANGUAGE = 1062,
	INVALID_ACCENT_COLOR = 1063,
	INVALID_ITEM_ID = 1064,
	ITEM_NOT_FOUND = 1065,
	INVALID_ITEM = 1066,
	ITEM_IN_USE = 1067,
	INVALID_TAX_PROFILE = 1068,
	INVALID_CUSTOMER_TYPE = 1069,
	VAT_CHECK_NOT_POSSIBLE = 1070,
	VAT_CHECK_UNAVAILABLE = 1071,
	INVALID_TAX_EXCHANGE_RATE = 1072,
	INVALID_REPORT_PERIOD = 1073,
	INVALID_CREDIT_NOTE = 1074,
	NOTHING_TO_CREDIT = 1075,
	CREDIT_NOTE_NOT_FOUND = 1076,
	INVALID_CREDIT_NOTE_ID = 1077,
	INVALID_SALE = 1078,
	CUSTOM_AMOUNTS_DISABLED = 1079,
	SALE_NOT_FOUND = 1080,
	SALE_LOCKED = 1081,
	INVITATION_NOT_FOUND = 1082,
	EMAIL_NOT_CONFIGURED = 1083,
	EMAIL_RECIPIENT_MISSING = 1084,
	EMAIL_LIMIT_REACHED = 1085,
	RECURRING_NOT_FOUND = 1086,
	INVALID_RECURRING = 1087,
	RECURRING_CLOSED = 1088,
	RECURRING_HAS_INVOICES = 1089,
	CUSTOMER_HAS_RECURRING = 1090,
	RECURRING_RUN_FAILED = 1091,
	INVALID_PROCESSOR_CONFIG = 1092,
	LICENSE_NOT_FOUND = 1093,
	LICENSE_ALREADY_REDEEMED = 1094,
	INVALID_LICENSE = 1095,
	TRANSACTION_LIMIT_REACHED = 1096,
	WHITE_LABEL_REQUIRED = 1097,
	ADMIN_REQUIRED = 1098,
	INVALID_SETTING = 1099,
	INVALID_LOGO = 1100,
	LICENSE_NOT_REVOCABLE = 1101,
	INVALID_EMAIL_SERVER = 1102,
	CANNOT_MODIFY_OWN_ACCOUNT = 1103,
	ACCOUNT_NOT_FOUND = 1104,
	EMAIL_SERVER_FAILED = 1105,
	INVALID_INVOICE_FORMAT = 1106,
	INVOICE_NUMBERS_EXHAUSTED = 1107,
	OUT_OF_STOCK = 1108,
	INVALID_ITEM_KEYS = 1109,
	ITEM_KEY_NOT_FOUND = 1110,
	ITEM_KEY_IN_USE = 1111,
	UNKNOWN_ERROR = 2000,
	INSUFFICIENT_PERMISSIONS = 9999,
}

export { Error as ErrorCode };

namespace Errors {
	export const list: { [key: number]: { message: string; httpCode: number } } = {
		0: { message: "Success", httpCode: 200 },
		404: { message: "Invalid API endpoint", httpCode: 404 },
		405: { message: "HTTP method is not allowed on this endpoint.", httpCode: 405 },
		1000: { message: "Bearer Token is missing in Authorization header.", httpCode: 401 },
		1001: { message: "Not all required data provided in json format.", httpCode: 400 },
		1002: {
			message:
				"Project name can only contain lowercase characters, numbers and hyphens. It also needs to start with lowercase character and be between 4 and 30 characters long.",
			httpCode: 400,
		},
		1003: {
			message:
				"Username can only contain lowercase characters, numbers and hyphens. It also needs to start with lowercase character and be between 4 and 30 characters long.",
			httpCode: 400,
		},
		1004: { message: "Password needs to be hashed with Blake2b. The length of hashed password needs to be 128 characters.", httpCode: 400 },
		1005: { message: "Project with this name already exists!", httpCode: 409 },
		1006: { message: "Provided project is invalid!", httpCode: 400 },
		1007: { message: "Account with provided username or email already exists.", httpCode: 409 },
		1008: { message: "Provided API Secret Key in Bearer Token is invalid.", httpCode: 401 },
		1009: { message: "Provided email is invalid.", httpCode: 400 },
		1010: { message: "Provided transactionID is invalid.", httpCode: 400 },
		1011: { message: "Username and Password are missing in Authorization header.", httpCode: 401 },
		1012: { message: "Provided username is invalid.", httpCode: 400 },
		1013: { message: "Provided password is invalid.", httpCode: 400 },
		1014: { message: "Password is incorrect.", httpCode: 401 },
		1015: { message: "Redis connection error.", httpCode: 500 },
		1016: { message: "Provided token is invalid.", httpCode: 401 },
		1017: { message: "Provided token is incorrect or it has expired.", httpCode: 401 },
		1018: { message: "Username and Token are missing in Authorization header.", httpCode: 401 },
		1019: { message: "Project does not exist.", httpCode: 404 },
		1020: { message: "You are not a member of this project.", httpCode: 403 },
		1021: { message: "Project member does not exist.", httpCode: 404 },
		1022: { message: "This account is already a member of the project.", httpCode: 409 },
		1023: { message: "Provided role is invalid.", httpCode: 400 },
		1024: { message: "A project must always have at least one owner.", httpCode: 409 },
		1025: { message: "You cannot change or remove your own membership.", httpCode: 403 },
		1026: { message: "This account has been suspended.", httpCode: 403 },
		1027: { message: "Provided member id is invalid.", httpCode: 400 },
		1028: { message: "Server is missing a valid RABBITPAY_MASTER_KEY in its environment.", httpCode: 500 },
		1029: { message: "Provided webhook URL is invalid. It must be a http:// or https:// URL.", httpCode: 400 },
		1030: { message: "Too many requests. Please slow down and try again later.", httpCode: 429 },
		1031: { message: "Customer does not exist.", httpCode: 404 },
		1032: { message: "Customer with this email already exists in this project.", httpCode: 409 },
		1033: { message: "Provided customer id is invalid.", httpCode: 400 },
		1034: { message: "Provided country is invalid. It must be an ISO 3166-1 alpha-2 code.", httpCode: 400 },
		1035: { message: "Invoice does not exist.", httpCode: 404 },
		1036: { message: "Provided invoice id is invalid.", httpCode: 400 },
		1037: { message: "Provided currency is invalid. It must be an ISO 4217 code.", httpCode: 400 },
		1038: { message: "Invoice must contain at least one valid item.", httpCode: 400 },
		1039: { message: "Invoice amounts must be whole numbers in the smallest currency unit and cannot be negative.", httpCode: 400 },
		1040: { message: "Provided due date is invalid.", httpCode: 400 },
		1041: { message: "Only draft invoices can be edited.", httpCode: 409 },
		1042: { message: "Invoice has already been canceled.", httpCode: 409 },
		1043: { message: "Invoice has already been paid.", httpCode: 409 },
		1044: { message: "Provided invoice status is invalid.", httpCode: 400 },
		1045: { message: "Customer cannot be deleted while invoices reference it.", httpCode: 409 },
		1046: { message: "Transaction does not exist.", httpCode: 404 },
		1047: { message: "Transaction amount must be a whole number in the smallest currency unit and greater than zero.", httpCode: 400 },
		1048: { message: "Provided processor is not supported.", httpCode: 400 },
		1049: { message: "Transaction currency must match the invoice currency.", httpCode: 409 },
		1050: { message: "Payments can only be recorded against an issued invoice.", httpCode: 409 },
		1051: { message: "Refund amount is higher than the amount still available to refund.", httpCode: 409 },
		1052: { message: "Only a completed payment can be refunded.", httpCode: 409 },
		1053: { message: "Provided transaction status is invalid.", httpCode: 400 },
		1054: { message: "This payment processor is not enabled on the server.", httpCode: 503 },
		1055: { message: "An exchange rate is required, given as units of the invoice currency per 1 BTC.", httpCode: 400 },
		1056: { message: "The configured account has no details for this currency.", httpCode: 409 },
		1057: { message: "Webhook signature could not be verified.", httpCode: 400 },
		1058: { message: "The payment processor could not be reached. Please try again shortly.", httpCode: 502 },
		1059: { message: "No exchange rate is available for this currency right now. Please try again shortly.", httpCode: 503 },
		1060: { message: "Provided date or time format is not one this server offers.", httpCode: 400 },
		1061: { message: "Provided supply date is invalid. It must be a timestamp in milliseconds.", httpCode: 400 },
		1062: { message: "Provided language is not one this server offers.", httpCode: 400 },
		1063: { message: "Provided accent color is invalid. It must be a hex color such as #4f46e5.", httpCode: 400 },
		1064: { message: "Provided item ID is invalid.", httpCode: 400 },
		1065: { message: "Item not found.", httpCode: 404 },
		1066: { message: "Provided item is invalid. It needs a name, a price in the smallest currency unit and a tax rate between 0 and 100.", httpCode: 400 },
		1067: { message: "This item appears on invoices, so it cannot be deleted. Archive it instead.", httpCode: 409 },
		1068: {
			message:
				"Provided tax settings are invalid. Country must be an ISO 3166-1 alpha-2 code, VAT status one of registered, small_business or not_registered, and currency an ISO 4217 code.",
			httpCode: 400,
		},
		1069: { message: "Provided customer type is invalid. It must be business or individual.", httpCode: 400 },
		1070: { message: "Only an EU VAT number can be checked. Add the country prefix, such as DE123456789, or set the customer's country.", httpCode: 409 },
		1071: { message: "VIES could not check the VAT number right now. Please try again in a few minutes.", httpCode: 503 },
		1072: {
			message:
				"Provided exchange rate is invalid. It must be a positive number of reporting currency units per one unit of the invoice currency, and the invoice must be issued in another currency.",
			httpCode: 400,
		},
		1073: { message: "Provided report period is invalid. Use from and to as timestamps in milliseconds, with from before to.", httpCode: 400 },
		1074: {
			message:
				"Provided credit note is invalid. Give an amount no higher than what is left to credit, or lines with an amount each, in the smallest currency unit.",
			httpCode: 400,
		},
		1075: { message: "Nothing is left to credit on this invoice.", httpCode: 409 },
		1076: { message: "Credit note does not exist.", httpCode: 404 },
		1077: { message: "Provided credit note id is invalid.", httpCode: 400 },
		1078: { message: "The sale needs at least one line, each with a saved item or an amount and a whole quantity.", httpCode: 400 },
		1079: { message: "Custom amounts are turned off for cashiers in this project.", httpCode: 403 },
		1080: { message: "Sale does not exist.", httpCode: 404 },
		1081: { message: "Only a manager can change this sale.", httpCode: 403 },
		1082: { message: "This invitation does not exist or was already used.", httpCode: 404 },
		1083: { message: "Email is not set up on this server.", httpCode: 503 },
		1084: { message: "There is no email address to send this to.", httpCode: 400 },
		1085: { message: "This has been emailed too many times already.", httpCode: 429 },
		1086: { message: "Recurring invoice does not exist.", httpCode: 404 },
		1087: {
			message: "A recurring invoice needs a customer, at least one line, a schedule of every 1 to 60 weeks, months or years, and a start date from today on.",
			httpCode: 400,
		},
		1088: { message: "This recurring invoice was canceled or has ended.", httpCode: 409 },
		1089: { message: "A recurring invoice that already created invoices cannot be deleted. Cancel it instead.", httpCode: 409 },
		1090: { message: "This customer has recurring invoices. Delete or cancel them first.", httpCode: 409 },
		1091: { message: "The invoice could not be created. The reason is shown on the recurring invoice.", httpCode: 500 },
		1092: { message: "The payment method settings are not valid.", httpCode: 400 },
		1093: { message: "This license key does not exist.", httpCode: 404 },
		1094: { message: "This license key was already used or revoked.", httpCode: 409 },
		1095: {
			message:
				"Provided license is invalid. A transactions license needs 1 to 100000000 transactions, a white label or online store license 1 to 3650 days, a storage license 1 to 1000000 GB, and at most 100 keys can be created at once.",
			httpCode: 400,
		},
		1096: {
			message: "This project has used its free payments for this month and has no paid transactions left. Redeem a transaction license to continue.",
			httpCode: 402,
		},
		1097: { message: "This needs an active white label license.", httpCode: 402 },
		1098: { message: "Only server administrators can do this.", httpCode: 403 },
		1099: { message: "Provided setting is invalid.", httpCode: 400 },
		1100: { message: "The logo must be a PNG, JPEG or WebP image of at most 150 KB.", httpCode: 400 },
		1101: { message: "Only a license key that was not used yet can be revoked.", httpCode: 409 },
		1102: { message: "The email server needs a host, a port between 1 and 65535 and a valid from address.", httpCode: 400 },
		1103: { message: "You cannot change your own administrator access or status.", httpCode: 403 },
		1104: { message: "Account does not exist.", httpCode: 404 },
		1105: { message: "The email server did not accept the test message.", httpCode: 502 },
		1106: { message: "The invoice number format or next number is not valid.", httpCode: 400 },
		1107: { message: "Invoice numbers for this period are used up. Add more X to the number format under Settings.", httpCode: 409 },
		1108: { message: "There are not enough keys left in stock for one of the items on this invoice.", httpCode: 409 },
		1109: { message: "Provide the keys as text with one key per line, at most 5000 keys of 500 characters each.", httpCode: 400 },
		1110: { message: "This key does not exist.", httpCode: 404 },
		1111: { message: "This key is already held for an invoice or was sent to a customer, so it cannot be removed.", httpCode: 409 },
		1112: { message: "Provide a description, category, currency, valid amounts and dates.", httpCode: 400 },
		1113: { message: "This expense does not exist.", httpCode: 404 },
		1114: { message: "This recurring expense does not exist.", httpCode: 404 },
		1115: { message: "This recurring expense has ended or was canceled.", httpCode: 409 },
		1116: { message: "This schedule changed while you were editing it. Reload and try again.", httpCode: 409 },
		1117: { message: "This report was generated recently. Wait until the next generation time.", httpCode: 429 },
		1118: { message: "This report is already being generated. Try again shortly.", httpCode: 409 },
		1119: { message: "Generate this report before exporting it.", httpCode: 409 },
		1120: { message: "Enter a full name of at most 150 characters and a valid drawn signature of at most 100 KB.", httpCode: 400 },
		1121: { message: "Attach a PDF, PNG, JPEG, WebP or TIFF file of at most 20 MB.", httpCode: 400 },
		1122: { message: "This expense has no attachment.", httpCode: 404 },
		1123: { message: "The DDV evidence contains errors that must be fixed before export.", httpCode: 409 },
		1124: { message: "This DDV export does not exist.", httpCode: 404 },
		1125: { message: "The DDV period must be one complete calendar month or calendar quarter.", httpCode: 400 },
		1126: { message: "This project has used its included document storage. Redeem a storage license to add more capacity.", httpCode: 402 },
		1127: { message: "Provided timezone is invalid. Use an IANA timezone such as Europe/Ljubljana.", httpCode: 400 },
		1128: { message: "This accounting period is locked after a DDV submission. Unlock it before changing accounting records.", httpCode: 409 },
		1129: { message: "This accounting period lock does not exist or was already unlocked.", httpCode: 404 },
		1130: { message: "Explain why this accounting period must be unlocked using 3 to 500 characters.", httpCode: 400 },
		1131: { message: "The accounting timezone cannot be changed after invoices or expenses have been recorded.", httpCode: 409 },
		1132: { message: "The invoice is missing information required before it can be issued.", httpCode: 409 },
		1133: { message: "A two-factor authentication code is required.", httpCode: 401 },
		1134: { message: "The two-factor authentication code is invalid or expired.", httpCode: 401 },
		1135: { message: "Two-factor authentication is already enabled for this account.", httpCode: 409 },
		1136: { message: "Two-factor authentication is not enabled for this account.", httpCode: 409 },
		1137: { message: "The two-factor setup expired. Start setup again.", httpCode: 410 },
		1138: { message: "The .p12 certificate could not be read. Check the file and its password.", httpCode: 400 },
		1139: { message: "This is not a valid FURS certificate for fiscal verification of invoices.", httpCode: 400 },
		1140: {
			message:
				"Fiscal verification with FURS is not set up for this project. Invoices paid in cash, by card or in crypto must be verified by FURS in Slovenia.",
			httpCode: 409,
		},
		1141: { message: "The business premise details are not valid.", httpCode: 400 },
		1142: { message: "FURS could not be reached. Try again in a moment.", httpCode: 503 },
		1143: { message: "FURS rejected the request.", httpCode: 422 },
		1144: { message: "This fiscal record does not exist.", httpCode: 404 },
		1145: { message: "Upload the FURS certificate first.", httpCode: 409 },
		1146: { message: "Register this business premise with FURS before using it.", httpCode: 409 },
		1147: { message: "Automatic backups only cover a SQLite database file.", httpCode: 409 },
		1148: { message: "The backup could not be stored.", httpCode: 502 },
		1149: { message: "A backup is already running.", httpCode: 409 },
		1150: { message: "This needs an active online store license.", httpCode: 402 },
		1151: {
			message: "The store settings are not valid. Check the web address, colors, links, opening hours, shipping options and page texts.",
			httpCode: 400,
		},
		1152: { message: "Another store already uses this web address.", httpCode: 409 },
		1153: { message: "This store does not exist or is closed.", httpCode: 404 },
		1154: { message: "A category needs a name of at most 120 characters and a web address made of lowercase letters, digits and dashes.", httpCode: 400 },
		1155: { message: "This category does not exist.", httpCode: 404 },
		1156: {
			message: "The product details are not valid. Check the web address, description, attributes, stock and delivery times.",
			httpCode: 400,
		},
		1157: { message: "This product does not exist or is not for sale.", httpCode: 404 },
		1158: { message: "The image must be a PNG, JPEG or WebP file of at most 5 MB.", httpCode: 400 },
		1159: { message: "This image does not exist.", httpCode: 404 },
		1160: { message: "A product can have at most 12 images.", httpCode: 409 },
		1161: { message: "The cart is empty or contains an invalid line.", httpCode: 400 },
		1162: { message: "One of the products in the cart is out of stock or does not have enough stock left.", httpCode: 409 },
		1163: { message: "This order does not exist.", httpCode: 404 },
		1164: { message: "The order change is not valid.", httpCode: 400 },
		1165: { message: "Another store already uses this domain.", httpCode: 409 },
		1166: { message: "The customer details are not valid. Check the name, address, country and VAT ID.", httpCode: 400 },
		1167: { message: "Accept the terms of sale and the privacy policy to place the order.", httpCode: 400 },
		1168: { message: "This store cannot take orders right now.", httpCode: 409 },
		1169: {
			message: "Confirm that delivery of the digital content starts right away and that you then lose the right of withdrawal.",
			httpCode: 400,
		},
		1170: { message: "The invoice design is not valid. Check the colors and the text lengths.", httpCode: 400 },
		1171: {
			message:
				"The email design is not valid. Check the color, the text lengths, that subjects and buttons are one line, and that texts only use the placeholders listed for each email.",
			httpCode: 400,
		},
		1172: { message: "The document is missing information required for an e-SLOG invoice.", httpCode: 409 },
		1173: {
			message: "The reference document is not valid. Choose an order or a contract, enter its number with at most 70 characters and a valid date.",
			httpCode: 400,
		},
		1174: { message: "The customer's bank account is not valid. Check the IBAN and the BIC.", httpCode: 400 },
		1175: { message: "The signing certificate could not be read. Check the file and the password.", httpCode: 400 },
		1176: { message: "The signing certificate cannot sign e-invoices.", httpCode: 409 },
		1177: {
			message: "The stored e-SLOG file failed its integrity check. Restore it from a backup of the document storage before sending it again.",
			httpCode: 500,
		},
		1178: { message: "This e-SLOG version does not exist.", httpCode: 404 },
		1179: { message: "This document is not available as an e-invoice right now. Please contact the seller.", httpCode: 409 },
		1180: { message: "The file could not be read as an e-SLOG 2.0 or UBL 2.1 invoice.", httpCode: 400 },
		1181: { message: "This supplier invoice has already been recorded as an expense.", httpCode: 409 },
		1182: { message: "New registrations are closed on this server.", httpCode: 403 },
		1183: { message: "Registration on this server needs an invite code.", httpCode: 403 },
		1184: { message: "This invite code is not valid, has expired or was already used up.", httpCode: 403 },
		1185: { message: "This server has reached its maximum number of accounts.", httpCode: 403 },
		1186: { message: "This invite code does not exist.", httpCode: 404 },
		1187: {
			message:
				"The invite code is not valid. Uses must be a whole number from 1 to 100000 or empty, the expiry in the future and the note at most 500 characters.",
			httpCode: 400,
		},
		1188: { message: "This invite code was already revoked.", httpCode: 409 },
		1189: { message: "This needs an active workforce license.", httpCode: 402 },
		1190: {
			message:
				"The time entry is not valid. Use a date, a start and end time within one day or overnight, a break shorter than the shift and a note of at most 2000 characters.",
			httpCode: 400,
		},
		1191: { message: "This time entry does not exist.", httpCode: 404 },
		1192: { message: "This time overlaps another entry on the same timesheet.", httpCode: 409 },
		1193: { message: "This day can no longer be changed from your timesheet. Ask a supervisor to correct it.", httpCode: 403 },
		1194: { message: "The absence is not valid. Choose a type, a start and end date in the right order and at most 366 days.", httpCode: 400 },
		1195: { message: "This absence does not exist.", httpCode: 404 },
		1196: { message: "This absence was already approved, rejected or canceled.", httpCode: 409 },
		1197: { message: "The workforce settings are not valid.", httpCode: 400 },
		1198: { message: "The day off needs a date and a name of at most 200 characters.", httpCode: 400 },
		1199: { message: "This day off does not exist.", httpCode: 404 },
		1200: { message: "There is already a day off on this date.", httpCode: 409 },
		1201: { message: "The ticket is not valid. It needs a title of at most 200 characters and a known type, status and priority.", httpCode: 400 },
		1202: { message: "This ticket does not exist.", httpCode: 404 },
		1203: { message: "The comment must have between 1 and 10000 characters.", httpCode: 400 },
		1204: { message: "This comment does not exist.", httpCode: 404 },
		1205: { message: "You cannot open this kind of ticket here.", httpCode: 403 },
		1206: { message: "There is no uninvoiced time on this ticket.", httpCode: 409 },
		1207: { message: "The employee details are not valid.", httpCode: 400 },
		1208: { message: "This person is not a member of the project.", httpCode: 404 },
		1209: { message: "This time was already invoiced and can no longer be changed.", httpCode: 409 },
		1210: { message: "The vacation balance must use whole or half days between 0 and 366.", httpCode: 400 },
		1211: { message: "Set an hourly rate on the ticket before invoicing its time.", httpCode: 409 },
		1212: { message: "This absence overlaps another absence that is pending or approved.", httpCode: 409 },
		1213: {
			message: "The tax table is not valid. Rates must be percentages, amounts whole cents and brackets increasing with the last one open.",
			httpCode: 400,
		},
		1214: { message: "There is no tax table for this month.", httpCode: 404 },
		1215: { message: "Check the tax table against the official values and mark it as checked before finalizing payroll.", httpCode: 409 },
		1216: { message: "This payroll run does not exist.", httpCode: 404 },
		1217: { message: "There is already a payroll run for this month.", httpCode: 409 },
		1218: { message: "This payroll run is final. Reopen it before changing it.", httpCode: 409 },
		1219: { message: "The payroll run needs a month and an optional payment date.", httpCode: 400 },
		1220: { message: "Payroll items need a type, a description of at most 200 characters and a positive amount.", httpCode: 400 },
		1221: { message: "This person is not part of the payroll run.", httpCode: 404 },
		1222: { message: "The REK-O file needs more data first.", httpCode: 409 },
		1223: { message: "The payment file needs more data first.", httpCode: 409 },
		1224: { message: "Finalize the payroll run first.", httpCode: 409 },
		1225: { message: "This coupon code is not valid for this order.", httpCode: 400 },
		1226: { message: "This coupon code has already been used up.", httpCode: 409 },
		1227: {
			message:
				"The coupon is not valid. Use a code of 3 to 32 letters, digits, dashes or underscores, a percent from 1 to 100 or a positive amount, and an end after the start.",
			httpCode: 400,
		},
		1228: { message: "This coupon does not exist.", httpCode: 404 },
		1229: { message: "Another coupon already uses this code.", httpCode: 409 },
		1230: { message: "This security key does not exist.", httpCode: 404 },
		1231: { message: "The security key could not be verified. Try again.", httpCode: 400 },
		1232: { message: "An account can have at most 10 security keys.", httpCode: 409 },
		1233: { message: "Name the security key using 1 to 64 characters.", httpCode: 400 },
		1234: { message: "Accept the Terms of Service to continue.", httpCode: 400 },
		1235: { message: "The Terms of Service or Privacy Policy changed. Review the current version and accept it again.", httpCode: 409 },
		1236: { message: "Write the document in at least one language, using at most 100000 characters per language.", httpCode: 400 },
		1237: { message: "This legal document does not exist.", httpCode: 404 },
		1238: { message: "Choose an effective date from today up to one year ahead, and not before the previous version takes effect.", httpCode: 400 },
		1239: { message: "This account is the only owner of projects other people use. Make someone else an owner first.", httpCode: 409 },
		1240: { message: "Only the RabbitPay license issuer can create license keys or change license limits.", httpCode: 403 },
		1241: { message: "This license key was issued for another server. Check the Server ID you gave when buying it.", httpCode: 409 },
		1242: { message: "This server only accepts license keys signed for its Server ID.", httpCode: 409 },
		1243: {
			message: "This project has more people in its workforce than its license covers. Redeem an employee seat license or remove people to continue.",
			httpCode: 402,
		},
		2000: { message: "Something went wrong while trying to perform this action. Please try again later.", httpCode: 500 },
		9999: { message: "Your do not have permission to perform this action.", httpCode: 403 },
	};

	export function get(id: Error) {
		return list[id];
	}

	export function getJson(id: Error) {
		return { error: id, info: list[id].message };
	}
}

export default Errors;
